

def main():
  with open('payload.bin', 'rb') as f:
    payload = f.read()
  with open('common/loader.c', 'r') as f:
    loader = f.read()
  shellcode = ''
  if True:
    for i in range(0, len(payload), 16):
      line = payload[i:i + 16]
      hex_line = '\\x'.join(f'{b:02x}' for b in line)
      shellcode += f'\t"\\x{hex_line}"\n'
      i += 16
  print('/* This file is auto-generated by common/craft.py */')
  print(loader.replace('__SIZE__', str(len(payload))).replace('__SHELLCODE__', shellcode))


if __name__ == '__main__':
  main()